name: version_blocker_flutter_example
description: Demonstrates how to use the version_blocker_flutter plugin.
version: 0.2.0+7
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase: ^9.0.2
  firebase_core: ^1.10.5
  firebase_database: ^9.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  package_info_plus: ^1.3.0
  version_blocker_flutter:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  store_redirect: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/update_alternative.jpg
    - assets/images/10772206.jpg