name: version_blocker_flutter_example
description: Demonstrates how to use the version_blocker_flutter plugin.
version: 0.2.0+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase: ^9.0.2
  firebase_core: ^1.10.5
  firebase_database: ^9.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  package_info_plus: ^1.3.0
  version_blocker_flutter:
    # When depending on this package from a real application you should use:
    #   wakelock: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path:../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  store_redirect: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/update_icon.jpg
