// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0kcxLyP50yxHlmX1E0gkFe9r9d-Gih40',
    appId: '1:304934947491:web:13bfa3edeb639ea636cd16',
    messagingSenderId: '304934947491',
    projectId: 'capsula-firebase',
    authDomain: 'capsula-firebase.firebaseapp.com',
    storageBucket: 'capsula-firebase.appspot.com',
    measurementId: 'G-1EPJ0FKJPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFkLvkptdP8G6ac-n8otsVmdO0iezLojs',
    appId: '1:304934947491:android:fe23d2f6cddaf5b636cd16',
    messagingSenderId: '304934947491',
    projectId: 'capsula-firebase',
    storageBucket: 'capsula-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzcbN5kleM__SZCEfHh1d6QBoa3P5ZCtI',
    appId: '1:304934947491:ios:b0e73eb9c2f0009f36cd16',
    messagingSenderId: '304934947491',
    projectId: 'capsula-firebase',
    storageBucket: 'capsula-firebase.appspot.com',
    iosClientId: '304934947491-480g00rlu9ldh4vucskkvs40top3umh0.apps.googleusercontent.com',
    iosBundleId: 'br.com.medcapsula.capsulacards',
  );
}
